/**
 * Bundles hash-wasm's UMD build into a TS string constant so the Argon2 WebView
 * bridge can inline it directly in the HTML instead of loading it from a CDN.
 * Re-run with `bun run gen:argon2` whenever the hash-wasm dependency is bumped.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const candidates = [
  join(root, "node_modules", "hash-wasm", "dist", "index.umd.min.js"),
  join(root, "node_modules", "hash-wasm", "dist", "index.umd.js"),
];
const outPath = join(root, "components", "argon2-umd.gen.ts");

function main() {
  const srcPath = candidates.find((p) => existsSync(p));
  if (!srcPath) {
    throw new Error(
      `hash-wasm UMD bundle not found (looked in: ${candidates.join(", ")}). Run "bun install" first.`,
    );
  }

  const source = readFileSync(srcPath, "utf8");
  const banner =
    "// AUTO-GENERATED by scripts/gen-argon2-bundle.ts - do not edit by hand.\n" +
    `// Source: ${srcPath.replace(root, "apps/native").split("\\").join("/")}\n\n`;
  const contents = `${banner}export const HASH_WASM_UMD = ${JSON.stringify(source)};\n`;

  writeFileSync(outPath, contents, "utf8");
  console.log(`[gen-argon2] wrote ${outPath} (${source.length} bytes from ${srcPath})`);
}

main();
